### ISSUE TITLE
Type annotation support

### ISSUE THREAD

**Issue by pierrejean-coudert** [JdeH/Transcrypt#105]
It would be great to use [mypy ](http://mypy.readthedocs.io/en/latest/index.html) in transcrypt compiler in order to have static type checking using [type annotations](https://docs.python.org/3/library/typing.html).

**Comment by JdeH** [comment]
Hi,

This is very interesting!
I have given some thought to static typechecking in connection with NumScrypt, to e.g. keep real and complex matrixes apart, since mixing them costs performance.
Didn't know this tool existed, do you have experience with it?
How mature / stable is it?

Kind regards
Jacques

**Comment by pierrejean-coudert** [comment]
MyPy is still marked as 'experimental' but is actively developped by some very well known contibutors ( https://github.com/python/mypy/graphs/contributors )... Guido himself !
It's already usefull and could lead transcrypt to be used in place of other typed languages ( Typescript, Elm, ...)

**Comment by JdeH** [comment]
I've got a strong 'yes' feeling with this one...

**Comment by scitesy** [comment]
Yay!

**Comment by JdeH** [comment]
Version 3.5.219 now  supports static typechecking expermentally (mypy is included in the distro), using the -ds command line switch. There's a simple example in manual_tests.
 KR
J

**Comment by pierrejean-coudert** [comment]
This is a great news :-). Thanks !

**Comment by JdeH** [comment]
Might be that some things aren't perfect yet, or even missing.
I am busy writing a static typing tutorial that will become part of the docs, with diverse examples.
Should you encounter any problems, let me know.

I've choosen to integrate a frozen version of mypy rather than make it separately pip-installable, since mypy is still in flux. Planning is to replace it by a new version every time mypy makes signifincant progress.

I've been using it (only a little) and I must say I like the clear errror reports. This certainly holds promise. Quite curious what I'll encounter when making examples for the tutorial.

**Comment by JdeH** [comment]
Transcrypt currently works with an old version of mypy that can't benefit from the 3.6 syntax additions.
Since I am using a homebrew API to connect to Transcrypt to mypy, I'll leave it that way for a while.
But I've contributed module api.py to mypy which is already in the docs. As soon as it is in the distribution, I'll attempt to upgrade Transcrypt to use the newest version of mypy.
