### ISSUE TITLE
Cyclic Imports

### ISSUE THREAD

**Issue by mdiener** [JdeH/Transcrypt#106]
I've noticed that Transcrypt does not allow cyclic imports, while in Python this isn't a problem. It might be somewhat of an edge case, and yes, I can probably re-factor my code to prevent this, but to be honest in JavaScript I do have cases where I import something from one class and in that class I import something from the other class (especially when both are static). But regardless, since Python supports it I imagine Transcrypt could/should/might support it too.

Test Setup
--------------
Folder Structure
```
├── app
│   ├── __init__.py
│   ├── one.py
│   └── two.py
├── application.py
└── index.html
```

application.py
```python
from app import one
from app import two

one.display()
two.display()
```
one.py
```python
import app.two

def get_nr():
    return 20

def display():
    print('from one: ' + str(app.two.get_nr()))
```
two.py
```python
import app.one

def get_nr():
    return 20

def display():
    print('from two: ' + str(app.one.get_nr()))
```
index.html
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <script type="text/javascript" src="__javascript__/application.js"></script>
</body>
</html>
```
Expected Behavior
------------------------
I expect to see the following lines printed in the console (on javascript/python)
```
from one: 20
from two: 20
```
Observed Behavior
------------------------
When I then import the file application.py in a regular python prompt I get the expected output of
```
from one: 20
from two: 20
```
However, upon loading the file through the browser, I receive the following error:
```
too much recursion
[...]
application/<.__all__.__init__()
application.js:1798
application/__init__()
application.js:41
application/<.__all__.__init__()
application.js:1823
application/__init__()
application.js:41
```
Conclusion
--------------
Not sure if this is really a bug or if this is just something that you decided on to be a limitation of Transcrypt, but I couldn't find anything about this in the documentation. I would love to see the possibility to have the same behavior in JavaScript as in Python, since that would make it a lot easier for me to write code. If, however, you decide this isn't something you want to implement, you can just close this ticket and I will find another way :)

**Comment by JdeH** [comment]
Hi,

The import mechanism of Transcrypt is deliberately simplified, although funny enough semantically it comes quite close to CPython's.

[http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#transcrypt-s-module-mechanism](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#transcrypt-s-module-mechanism)

It is also different in this sense that imports have to be decided upon compile time, since the code of the imported module has to be yes or no compiled at compile time. So another difference is that an import cannot be under an if (but rather under a \_\_pragma\_\_ ('ifdef', ...

I must say I hadn't foreseen your usecase, but it is perfectly valid and indeed CPython allows for it.
Looking into the current implementation I can see no lean way to realise this.
Since the 90/10 rule is a basic design principle of Transcrypt, I'll leave it out.

So I'll mark it as a limitation and add a hint to the docs.

Kind regards
Jacques
