### ISSUE TITLE
Request for Watchdog Integration

### ISSUE THREAD

**Issue by nueverest** [JdeH/Transcrypt#107]
Could you integrate [watchdog](https://github.com/gorakhargosh/watchdog) so that watchdog will continuously scan *.py files for file modification events and trigger Transcrypt?

I've found watchdog quite enjoyable to use.  It saves lots of context switching between the code and transcript.  Though sometimes the modification event is triggered twice on some OS's.  I've gotten around this by setting a three second timer that treats the consecutive triggers as one event. This also filters out quick user code changes between save events.  

Here is how I used it with blowdrycss: https://github.com/nueverest/blowdrycss/blob/master/blowdrycss/watchdogwrapper.py

**Comment by JdeH** [comment]
I am a bit in doubt about this one.

If a watchdog would be added, probably the easiest thing is to have Transcrypt do the watching itself (steered by a command line switch), since it can easily obtain a module list.

However, having a watchdog of any kind would mean that each time you save a modified file, (partial) recompilation takes place, which could be rather timeconsuming, especially the minification. To avoid that, a waiting time longer than 3 secs could be applied, but that would make watching sluggish.

Since you seem to be using PyCharm (I have no experience with it), doesn't it have a button that can be configured to trigger a remake, so you can simply choose when to make or build, after some edits and intermediate saves? And could that same button then launch the browser to see the result. In that case this wouldn't require an extra action, since the browser would have to be refreshed anyhow.

Or am I missing something?
Let me know what you think.

Jacques

**Comment by nueverest** [comment]
It would be possible to build a plugin for pycharm that triggers it, but it is not a simple task.

Having a flag that turns minification off in a watchdog mode would make sense in a development environment.

**Comment by JdeH** [comment]
I don't immediately have a yes-feeling with this feature.
Also a bit amazed that PyCharm doesn't allow easy integration of any kind of post-processing.
But as said I've no experience with it.
It seems so much more concise to make recompilation a side-effect triggered by a save (or controlled by a make, build or run button) in some editor or IDE, than to constantly scan a set of files to find out if anything changed.
For now I'll categorize it as 'under consideration'.
By the way, the -n flag turns of the minification.

**Comment by nueverest** [comment]
Okay. I can look deeper into ways of have PyCharm do it.  I can also just use watchdog's command line interface.

Thanks for the tip on the -n flag.  I noticed that there are lots of flags and hadn't studied that one yet.

**Comment by nueverest** [comment]
I should note that PyCharm does have support for Typescript and Coffescript via plugins.  There is also ES6 --> ES5.1 transpiling.

**Comment by nueverest** [comment]
PyCharm does have a FileWatcher plugin.  With a custom option.

![image](https://cloud.githubusercontent.com/assets/2917370/18154335/97222e08-6fb8-11e6-85a3-0414448b334f.png)


![image](https://cloud.githubusercontent.com/assets/2917370/18154359/b949d9d6-6fb8-11e6-8f9c-fb7be6b53e2f.png)

**Comment by JdeH** [comment]
Does this mean you can probably achieve what you want using PyCharm?

**Comment by nueverest** [comment]
Yes
