### ISSUE TITLE
module 'site' has no attribute 'getsitepackages'

### ISSUE THREAD

**Issue by sirex** [JdeH/Transcrypt#13]
Could not make it work:

```bash
> python --version
Python 3.5.1
> transcrypt -b testme.py                                          
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.113
Copyright (C) Geatec Engineering. License: Apache 2.0


module 'site' has no attribute 'getsitepackages'Ready
> cat testme.py 
for i in range(10):
    console.log(i)
```

**Comment by JdeH** [comment]
Thanks, 

This is an issue with virtualenv.
I'll add some kind of fix like.

    except:
        os.path.dirname(site.__file__) + "/site-packages"

https://github.com/pypa/virtualenv/issues/228

"
Yes, one of the uglier aspects of virtualenv's implementation is that it has to have its own copy of the site module, which is used for all virtualenvs regardless of which version of Python they are created with. And this copy predates the addition of site.getsitepackages() (first added in Python 2.7, I believe).

I would have no objection to a pull request adding that function to virtualenv's site module, as long as the implementation is one that can work on all virtualenv-supported versions of Python (2.4 through 3.3a). Or if that's too difficult due to missing APIs in other areas of the earlier Python versions, perhaps have it conditionally defined depending on sys.version or something.
"

**Comment by JdeH** [comment]
@sirex

V3.5.114 was committed, which contains a fix for this.
Could you please let me know if this works for you.

Kind regards
Jacques

**Comment by sirex** [comment]
Thanks, it worked!
