### ISSUE TITLE
pip3 install problem: ImportError: No module named 'org'

### ISSUE THREAD

**Issue by niki-sp** [JdeH/Transcrypt#2]
after "pip3 install transcrypt" on ubuntu 15.10 i get

ImportError: No module named 'org'

while trying >>> import Transcrypt.transcript

**Comment by JdeH** [comment]
Hi,
You don't have to import Transcrypt, it's a compiler, not a library.
After installing it (no pip, just copy and extract, currently, see docs), you use it like this:

transcrypt <myMainFileName>.py

You then get a JS file in the __javascript__ directory.
The <myFileName>.mod.js file is the code for your main module.
The <myFileName>.js and <myFileName>.min.js include the Transcrypt runtime and any encapsulated JS libs.
Note that  you don't have to encapsulate the JS libs, you can load them on the fly from a CDN.
But the runtime is always included, since joined minification gives smaller files due to identifier shortening.

Maybe it's best to start out by compiling and running the hello.py demo, and then make small alterations and building it out from there.

Also take a look at the HTML files in the examples to see how Transcrypt is used there.

**Comment by niki-sp** [comment]
Ok i can clone and install it. My suggestion is to support pip3 install for easier adoption.

**Comment by JdeH** [comment]
I will. Just focused on the Alpha rightnow. But it's agreed that installation should as easy as possible.

**Comment by Shaafihiy** [comment]
i try importing the following
import org.opensim.utils as utils
i got an error saying 'No module named org'
someone assist me on this please
