### ISSUE TITLE
Using underscore's extend from a Python class

### ISSUE THREAD

**Issue by miguelgrinberg** [JdeH/Transcrypt#20]
How would you go about using [Underscore](http://underscorejs.org/#extend) style inheritance? I'm thinking specifically about writing a [Backbone](http://backbonejs.org/) app in Python code, which means I need to create a bunch of Python classes that "extend" these Javascript "fake" classes such as `Model`, `Controller`, etc.

**Comment by JdeH** [comment]
I would expect you can use Underscore style inheritance and "plain" js classes side by side with Transcrypt inheritance.

Maybe there's a more clever way, but I currently lack the detailled knowledge of Underscore to know what that way is. Since Underscore is an important library and Transcrypt should be able to interop with  it I expect to look at it in due time.

**Comment by miguelgrinberg** [comment]
Thanks. First, let me show you a quick example of how you make a subclass in pure JS using underscore's inheritance:

    var Todo = Backbone.Model.extend({
      defaults: function() {
        return {
          title: "empty todo...",
          order: Todos.nextOrder(),
          done: false
        };
      },
      toggle: function() {
        this.save({done: !this.get("done")});
      }
    });

In this example, `Model` is part of the Backbone framework. It gets the `extend()` function from underscore. I'm defining a subclass of it by passing a JS object with the overloaded or new methods to this function. I assume I can literally translate this to Python, and pass a `dict` to the `extend()` function, but I was hoping to use a Python class, maybe something like this:

    class Todo(Backbone.Model):
        def defaults(self):
            return {'title': 'empty todo...', 'order': Todos.nextOrder(), 'done': false}
        def toggle(self):
            this.save({'done': !self.done})

I'll keep playing with this and see if I figure a good way to do this. If I do, I'll submit a small demo for your repo.

**Comment by JdeH** [comment]
I  know that this is not what you're looking for in the end, but to be complete, in Transcrypt the JS code would translate to something like (untested, and the 'this' pointer probably will have to be something else):

	Todo = Backbone.Model.extend ({
		'defaults': lambda {
			'title': 'empty todo...',
			'order': Todos.nextOrder (),
			'done': False
		},
		'toggle': lambda {
			this.save ({'done': not this.get ('done')})
		}
	})

**Comment by miguelgrinberg** [comment]
Yes, I'm pretty sure you can make Backbone work if you port the JS version sentence by sentence, but that really makes the Python code look like JS, so it defeats the purpose of writing Python. :)

It seems as a general rule, integration with JS libraries or frameworks that provide a system for classes and inheritance will not integrate with Transcrypt's own classes, at least not at this time. So if you want to write a single-page app with Backbone, Angular, etc. you have to use the class system provided by the JS side.

**Comment by JdeH** [comment]
The only thing I can think of rightnow, is that for larger applications, that have significant algorithmic and domain related stuff going on, I tend to make my domain class hierarchy independent of any tools and libs I use anyhow. (such that for instance they may run on the desktop or in the browser). By domain class hierarchy I mean classes that directly model entities and relations in my application domain rather than interface with databases, GUI's or browsers.

In that case the domain class hierarchy will be in one or more separate modules, and it can use Transcrypt's multiple inheritance mechanism. If written with some restraint it would work just as well with CPython as with Transcrypt, since it's platform and tool independent. The main thing in that case is to have a thin, stable interface between the modules, not leaking such implementation details.

I don't know how this will wear in practice with Transcrypt, since I myself have still grossly insufficient experience in using it (spending most of my time writing it.). Once I gain more experience using it for bigger real world apps, I hope to come across some design patterns that can be used as best practice examples when encountering dilemma's related to this.

So indeed, if you encounter patterns that could help, please submit them as a demo for others (and me) to benefit from.
