### ISSUE TITLE
del list[n] not translated correctly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#29]
```
foo = ['bar', 'baz']
del foo[0]
#foo.pop(0)  # workaround
print("foo len", len(foo), foo)

prints: "foo len 2 ,baz"

```

**Comment by JdeH** [comment]
Thanks, will be fixed in the next version.

**Comment by JdeH** [comment]
Sorry to get back on this.
It was left out because the del function in general was not yet implemented.
Since there are other was to achieve the same, for now I prefer to leave it out in the ever lasting search for the balance between compactness and completeness.
This is clearly a borderline case though.
It may make it as an enhancement in a later version, not sure yet.

**Comment by erelsgl** [comment]
I ran into the same issue:

```
    a = [1,2,3,4]
    del a[0]
    print(a)
```

It prints `[None, 2, 3, 4]` instead of `[2, 3, 4]`.

If I own the code, I can solve it by replacing "del" with "pop" everywhere.  However, if I use code from a third party, it may be very hard to go through all this code and replace "del" with "pop". Also, this bug causes a lot of confusion, since code that works perfectly on the server side, suddenly crashes or makes hard-to-find bugs in the client side.
