### ISSUE TITLE
Python list += list not translated correcctly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#38]
Python
```
a = [1, 2, 3]
a.append(4)
print(a)
a += [5, 6, 7]
print(a)
```
[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7]
Generated Javascript
```
var a = list ([1, 2, 3]);
a.append (4);
print (a);
a += list ([5, 6, 7]);
print (a);
```
[1, 2, 3, 4]
1,2,3,45,6,7

**Comment by JdeH** [comment]
Hi,

The + and += operators have not been overloaded for lists, since that would introduce overhead for every + in a program. This is because the operand types would only be known at runtime.

Operator overloading is mainly used for NumScrypt (and can be used for user classes).
To still be able to concatenate lists (which are plain JS arrays) efficienty to enable seamless interoperation with JS libs, itertools.chain has been implemented, as is illustrated here: [http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/installation_use.html#your-first-transcrypt-program](here)
