### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by dirkk0** [JdeH/Transcrypt#5]
Hi,

  I couldn't get transcrypt to work on an Ubuntu15 machine. Here's what I did:
- I added the directory to the path
- I cd'ed to the path Transcyrpt/development/automated_tests/transcrypt
- I ran 'transcrypt' which gives me

    Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.70
    Copyright (C) Geatec Engineering. License: Apache 2.0
    
    Usage: transcrypt.py [-h] [-k] [-b] [-l] [-r] [-v] [source

So from that I figured that the installation is ok.
- I ran 'transcrypt -b autotest.py' which gave me

    Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.70
    Copyright (C) Geatec Engineering. License: Apache 2.0
    
    
    [Errno 2] No such file or directory: 'java'Ready

What am I doing wrong?

Thanks,
  Dirk

**Comment by JdeH** [comment]
The problem is in starting the Google closure minifier, which needs java to run.

It is started by transcrypt/Transcrypt/modules/org/trancrypt/minify/__init__.py as follows:

	def run (sourcePath, targetPath):
		subprocess.run (['java', '-jar', closureCompilerPath, '--language_in=ES5', '--language_out=ECMASCRIPT5_STRICT', '--compilation_level', 'SIMPLE_OPTIMIZATIONS', '--js', sourcePath, '--js_output_file', targetPath])

Since I want Transcrypt also to be able to run without minification, I'll add a command switch for that.
If  you want to use the minifier, I am afraid you'll have to look into your java installation. Just typing 'java' at any command prompt should get you something like:

Usage: java [-options] class []args...] etc., (a screen full of info)
Let me know if this indeed was the problem.
I'll let you know as soon as the version with the switch is uploaded to GitHub.

Kind regards
Jacques

**Comment by dirkk0** [comment]
ok, cool!

Actually, I try to avoid Java at all costs (with the notable exception of Minecraft, which is not on my dev machine).

Is there a way to have transcrypt only doing the transpiling part, like so?
transcrypt source.py >target.js
I'd rather manage the creation of the HTML page etc myself.

**Comment by JdeH** [comment]
Hi Dirk,

1. You can now compile without minification, so without Java by using the -n switch.
2. The HTML files are only generated for the autotest, try e.g. compiling the pong example. The only file you need is the <target>.js file in the __javascript__ directory where your <source>.py is located. With pong that would be demos/pong/\_\_javascript\_\_/pong.js. Note that the Java will in no way be part of the distribution anyhow, it's just to do the minification on your development machine, it won't be on the webserver. By the way if you use minification the only file you need is <source>.min.js rather than <source>.js.

**Comment by dirkk0** [comment]
Hi Jacques,

  thank you, works like a charm!

Just for reference: I made transcrypt executable with 'chmod +x transcrypt' and instead of setting the path, I called it with '../../transcrypt -n hello.py'.

Best,
  Dirk

**Comment by JdeH** [comment]
OK, thanks, I'll keep that in mind for the docs.
