### ISSUE TITLE
dict missing clear(), setdefault()

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#54]
Python
d = {1: 11, 2: 22, 3: 33}
print("d = {1: 11, 2: 22, 3: 33} = ", d)
d.clear()
print("d.clear() = ", d)

d = {1: 11, 2: 22, 3: 33} =  {1: 11, 2: 22, 3: 33}
d.clear() =  {}

Generated javascript
var d = dict ({1: 11, 2: 22, 3: 33});
		print ('d = {1: 11, 2: 22, 3: 33} = ', d);
		d.clear ();
		print ('d.clear() = ', d);
TypeError: d.clear is not a function

Python
d = {}
d.setdefault('foo', 0)
d['foo'] += 1
d.setdefault('foo', 0)
d['foo'] += 1
print("d['foo'] = ", d['foo'])

d['foo'] =  2

Generated javascript
var d = dict ({});
		d.setdefault ('foo', 0);
		d ['foo']++;
		d.setdefault ('foo', 0);
		d ['foo']++;
		print ("d['foo'] = ", d ['foo']);
TypeError: d.setdefault is not a function

**Comment by JdeH** [comment]
This is one point where I hesitated between lean and complete. Rather than clearing a dictionary I most often just instantiate a new one (which of course doesn't work if there are references to the old dict spread all over.

And as far as setdefault is concerned, I seems to me like something that isn't often used.

But that's my personal 'usage pattern'. Maybe yours differs. Is one of these functions valuable to you? Or maybe both? In that case I'll add them, since they're both small.

Let me know in your reply.

Kind regards
Jacques

**Comment by shaolo1** [comment]
The reference issue you mention seems like it would put clear() in the important column.  I've not encountered that yet.  I used clear when I needed to clear a list and a set.  I was surprised to see that not work for dict.  

As for setdefault, I was just just reporting what I found.  The code is not as elegant, but there is a workaround for that.

**Comment by JdeH** [comment]
I will add 'clear' and for now leave out 'setdefault', since its use may indeed be rare.

**Comment by JdeH** [comment]
Committed

**Comment by AXGKl** [comment]
I beg to reconsider setdefault, working around it feels to me clumsy. 

I think this one would match Transcrypts' criteria, balancing bloat versus gain: widespread usage, [not only me](https://github.com/search?utf8=%E2%9C%93&q=setdefault+language%3Apython&type=Code&ref=searchresults)  or alone 31 occurances e.g. in sphinx and trivial to implement, imho (?)

**Comment by JdeH** [comment]
I will add it in the next commit
