### ISSUE TITLE
Names not exported from package's __init__.py

### ISSUE THREAD

**Issue by ceronman** [JdeH/Transcrypt#55]
Hello! I have been playing with Transcrypt today. It's such a great project!

I have found a difference in behaviour from CPython. I'm not sure if this is intentional or just a bug. I hope that filing this issue was the correct way of reporting it.

In CPython, names imported by a package's `__init__.py` are usually exported. In Transcrypt, these names are not exported.

Here is a small example of how to reproduce the issue:

```python
# ./export.py
from test import f1
f1()
```

```python
# ./test/__init__.py
from test.a import f1
```
```python
#./test/a.py
def f1():
    pass
```

When running `transcrypt -nr export.py` I get an error: 
```
ImportError: cannot import name 'f1'
```
However, running it with CPython works just fine, because the names imported in `__init__.py` are automatically exported as part of the package.

**Comment by JdeH** [comment]
Hi

Thanks for your correct observation and clear example.
I wasn't aware that CPython behaves this way....

There are intentional differences, mostly simplifications, between the Transcrypt and CPython import mechanism, but this one wasn't intentional.

I cannot oversee right now what it would take to build this behavior into Transcrypt.
At first sight it seems doable without much overhead, but I have to look into it deeper, sometimes small things have unforeseen consequences.

I'll register it as an enhancement, try to find out what it takes and then get back on this subject.

**Comment by JdeH** [comment]
I've committed a fix for this. Note that Transcrypt's import mechanism is still a simplification from Python's. E.g. __all__ isn't supported in the way Python does. Still this fix is important. I've used this facility myself many times without ever being aware of it... Let me know if this works for you.

**Comment by ceronman** [comment]
Thank you very much for the quick fix! I understand the goal of the project is not to have 100% CPython compatibility but rather to achieve as much compatibility while staying in the JS world, which is a very nice goal in my opinion. I'll keep playing with it and possibly will submit more issues here.
