### ISSUE TITLE
Adding two list

### ISSUE THREAD

**Issue by artyprog** [JdeH/Transcrypt#65]
Hello Jacques,
Adding two lists return NaN
Regards

**Comment by JdeH** [comment]
Hi Artyprog,

The + operator hasn't yet been overloaded for lists. I haven't done that because without  special measures even 1 + 1 would then result in a function call. This is because Python is dynamically typed and a + b might mean adding 2 lists or adding 2 ints etc.

As a workaround, currently lists can be concatenated with itertools.chain.

However there's the \_\_pragma\_\_ ('opov') to switch on operator overloading locally. I will provide lists with an __add__ method, which should make the list1 + list 2 work, if operator overloading is indeed switched on.

Because of the overhead probably you should indeed only use it locally. Transcrypt strikes a balance between speed and compactness on one hand, and completeness on the other.

I will add operator overloading for list addition in the next version, together with a demo, and keep you informed.

Kind regards
Jacques

**Comment by artyprog** [comment]
Tank you Jacques

Sent from my ASUS

-------- Message d'origine --------
De :Jacques de Hooge <notifications@github.com>
Envoyé :Sat, 25 Jun 2016 11:08:58 +0200
À :JdeH/Transcrypt <Transcrypt@noreply.github.com>
Ci :ArtyProg <salvatore.didio@gmail.com>,Author <author@noreply.github.com>
Sujet :Re: [JdeH/Transcrypt] Adding two list (#65)

**Comment by JdeH** [comment]
This feature has been added in 3.5.193
Switch in on with \_\_pragma\_\_ ('opov')
Switch it off again with \_\_pragma\_\_ ('noopov')

Like this:

    autoTester.check ('Issue 65')
	__pragma__ ('opov')
	aList = [4, 5, 6]
	autoTester.check ([1, 2, 3,] + aList + [4, 5, 6])
	autoTester.check (3 * [1, 2, 3])
	autoTester.check ([1, 2, 3] * 3)
	aString = 'Crocodile'
	autoTester.check ('Tiger' + aString + 'Elephant')
	autoTester.check (3 * aString)
	autoTester.check (aString * 3)
	__pragma__ ('noopov')

**Comment by artyprog** [comment]
Thank you Jacques....

2016-06-25 17:51 GMT+02:00 Jacques de Hooge <notifications@github.com>:
