### ISSUE TITLE
with statements

### ISSUE THREAD

**Issue by gbylenok** [JdeH/Transcrypt#70]
I am seeing errors when trying to compile a "with" statement without an "as" expression. For example:

```
 with self.set_values(keys):
            logger.debug("Do stuff")
            elem, elem = self.build_xml()`
```
However, the following completes without error:

```
with self.set_values(keys) as f:
            logger.debug("Do stuff")
            elem, elem = self.build_xml()
```

Looking at the grammar, it appears that the "as" expression is definitely optional:

`with_stmt: 'with' with_item (',' with_item)*  ':' suite`
`with_item: test ['as' expr]`

Unfortunately, the error message wasn't very helpful. It just pointed to the module and line number in question, with no useful message beyond that.

This is with version 3.5.161.

**Comment by JdeH** [comment]
Thank you for the feedback.
This is a bug, I'll look into it for the next version.

Jacques

**Comment by JdeH** [comment]
Things were a bit differently from what I remembered.
Currently in Transcrypt the with-statement is just a convenient way to open a file and not forget to close it again.

Since this opened file has to have a name to be able to read from it or write to it in the "body" of the with-statement, in this special case something has to be behind the as.

Of course in CPython the purpose of the with-statement is much broader: it will in general free any resources or do any cleanups needed in case of an exception. It can be used for all kinds of objects, not only files.

This broad, very useful, semantics of the with statement haven't been implemented yet, since (shame on me) I haven't used it very often after it got introduced into Python.

Having a with-statement with broader semantics (an hence a useful meaning without the 'as') is certainly desirable. So at some point I'll have to look into that.

For now I change the status from 'bug' (something accidentally overlooked) to 'enhancement' (something willfully overlooked for now). I plan, however, to get back on this one and see if Transcrypt can get closer to Python while maintaining its compactness and speed.

**Comment by JdeH** [comment]
The with statement is added in Transcrypt 3.7.3, using the ideas from #531 .
